ID:  BIS_GNN_S1_Resnet50MCD_SGD0005_cosine20_BS64_BCE_all_step_BNcls
COMMENT:
MODE: GNN

PRETRAINED_GNN_MODEL:
#  /mnt/rhome/elg/Repositories/GNN-Cross-Camera-Association/results/GNN_S1_Resnet50MCD_SGD0005_cosine20_BS64_BCE_all_step_BNcls_2021-11-03 10:58:05/files/GNN_S1_Resnet50MCD_SGD0005_cosine20_BS64_BCE_all_step_BNcls__best.pth.tar
#  /mnt/rhome/elg/Repositories/GNN-Cross-Camera-Association/results/GNN_trainTerr_Lab_Resnet50MCD_Adam0001_BS16_BCE_all_step_BNcls2021-11-02 10:06:36/files/GNN_trainTerr_Lab_Resnet50MCD_Adam0001_BS16_BCE_all_step_BNcls_best.pth.tar
#  /home/elg/Repositories/GNN-Cross-Camera-Association/results/GNN_trainPETSyTerrace_resnet_app_dist_distx_disty_erase0.252021-07-09 10:42:28/files/GNN_trainPETSyTerrace_resnet_app_dist_distx_disty_erase0.25_best.pth.tar

#FOR GNN
DATASET_TRAIN:
    NAME: [EPFL-Laboratory, EPFL-Terrace] # PETS2009_S2_L1_5_8 CAMPUS_Garden1
    ROOT: /mnt/rhome/elg/Datasets/
    IMAUG: True
    RESIZE:
      resnet50: [128, 64]
      bdnet_market: [384, 128]
      bdnet_cuhk: [384, 128]
      osnet_market: [256, 128]
      osnet_ms_c_d: [256, 128]
      resnext101_cars: [320, 320]

    CROP:
    FRAME_SAMPLING:
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    ZERO_PADDING: False

DATASET_VAL:
    NAME: EPFL-Basketball #EPFL-Basketball
    ROOT: /mnt/rhome/elg/Datasets/
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    ZERO_PADDING: False

POSITIVE_WEIGHT:
  AIC20-S01: 9
  EPFL-Laboratory: 4.5
  EPFL-Terrace: 4.5
  EPFL-Basketball: 4.5

CONV_TO_M: # dist/CONV_TO_M to covert to meters
  PETS2009_S2_L1_5_8: 26.56
  EPFL-Laboratory: 44.23
  EPFL-Terrace: 50.83
  CAMPUS_Garden1: 85.23
  AIC20-S01: 0.00001
  AIC20-S02: 0.00001
  EPFL-Basketball: 153.54


TRAINING:
    LOSS:
      NAME: BCE #Focal BCE_weighted  BCE
    BATCH_SIZE:
        TRAIN: 64
        VAL: 64
    EPOCHS: 20
    OPTIMIZER:
#      Adam 0.001
      type: SGD
      args:
        lr: 0.005
        weight_decay: 1.0e-4 #number of epochs
        momentum: 0.9
    LR_SCHEDULER:
      type: COSINE #STEP #COSINE
      args:
        step_size: 20
        gamma: 0.1

    WARMUP:
      ENABLE: True
      NUM_EPOCHS: 5
      LR: 0

    ONLY_APPEARANCE: False
    ONLY_DIST: False

CNN_MODEL:
    arch: resnet50 #resnet50 , bdnet_market, bdnet_cuhk, osnet_market, osnet_ms_c_d,resnext101_cars
    model_weights_path:
        resnet50: ./trained_models/reid/resnet50_market_cuhk_duke.tar-232
        bdnet_market: ./trained_models/top-dropblock/de00143e-market-model.pth.tar-400
        bdnet_cuhk: ./trained_models/top-dropblock/fbdaf3bb-cuhk-det-model.pth.tar-400
        osnet_market: ./trained_models/osnet/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth
        osnet_ms_c_d:  ./trained_models/osnet/osnet_ms_d_c.pth.tar
        resnext101_cars: ./trained_models/vehicle-reid/resnext_101_multihead.pth
    L2norm: True

DATALOADER:
    NUM_WORKERS: 4
    PIN_MEMORY: True


GRAPH_NET_PARAMS:
  node_agg_fn: 'sum'
  num_enc_steps: 4  # before 4 Number of message passing steps
  num_class_steps: 3  # before 3 Number of message passing steps during feature vectors are classified (after Message Passing)
  reattach_initial_nodes: False  # elg. Original: False Determines whether initially encoded node feats are used during node updates
  reattach_initial_edges: False  #  elg. Original: TrueDetermines whether initially encoded edge feats are used during node updates

  encoder_feats_dict:
    edges:
      edge_in_dim: 4 # elg: 2 if only appearance or only dist
      edge_fc_dims: [ ] #elg before [6]
      edge_out_dim: 6 # elg: original = 16 ours 1 if not encoding

    nodes:
      resnet50:
        #NODE FEATURES ENCODER
        node_in_dim: 2048
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False

      bdnet_market:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      bdnet_cuhk:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [ 128 ]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      osnet_ms_c_d:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False #False
      osnet_market:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      resnext101_cars:
        #NODE FEATURES ENCODER
        node_in_dim: 2048
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False


  # MPN EDGE UPDATE
  edge_model_feats_dict:
    fc_dims: [6] #  before 66,6elg: orig [80,16]In size is 4 * encoded nodes + 2 * encoded edges
    dropout_p: 0
    use_batchnorm: False

# MPN NODE UPDATE

  node_model_feats_dict:
    fc_dims: [32]  # elg: orig [56,32] In size is 2 * encoded nodes + 1 * encoded edges
    dropout_p: 0
    use_batchnorm: False

  classifier_feats_dict:
    edge_in_dim: 6 #orig 16
    edge_fc_dims: [4] # orig
    edge_out_dim: 1
    dropout_p: 0
    use_batchnorm: True