ID: name
COMMENT:
MODE: GNN_eval

#FOR GNN EVAL
ROUNDING: False
PRUNING: False
SPLITTING: False
PRETRAINED_GNN_MODEL: ./path/to/trainedGNNmodel


#FOR eval_RANK

RANK: 1
RERANK: True

DATASET_TRAIN:
    IMAUG: True
    RESIZE:
      resnet50: [128, 64]
      bdnet_market: [384, 128]
      bdnet_cuhk: [384, 128]
      osnet_market: [256, 128]
      osnet_ms_c_d: [256, 128]
      resnext101_cars: [320, 320]
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]

CONV_TO_M: # dist/CONV_TO_M to covert to meters
  PETS2009_S2_L1_5_8: 26.56
  EPFL-Laboratory: 44.23
  EPFL-Terrace: 50.83
  CAMPUS_Garden1: 85.23
  AIC20-S01: 0.00001
  AIC20-S02: 0.00001
  EPFL-Basketball: 153.54


#FOR GNN

DATASET_VAL:
    NAME: EPFL-Laboratory  #PETS2009_S2_L1_5_8 #EPFL-Laboratory #AIC20-S02
    ROOT: ./datasets/
    N_CLASSES:
    CROP:
    FRAME_SAMPLING:
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    ZERO_PADDING: False


TRAINING:
    BATCH_SIZE:
        VAL: 1

    ONLY_APPEARANCE: False
    ONLY_DIST: False

CNN_MODEL:
    arch: bdnet_market #resnet50 , bdnet_market, bdnet_cuhk, osnet_market, osnet_ms_c_d,resnext101_cars
    model_weights_path:
        resnet50: ./trained_models/reid/resnet50_market_cuhk_duke.tar-232
        bdnet_market: ./trained_models/top-dropblock/de00143e-market-model.pth.tar-400
        bdnet_cuhk: ./trained_models/top-dropblock/fbdaf3bb-cuhk-det-model.pth.tar-400
        osnet_market: ./trained_models/osnet/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth
        osnet_ms_c_d:  ./trained_models/osnet/osnet_ms_d_c.pth.tar
        resnext101_cars: ./trained_models/vehicle-reid/resnext_101_multihead.pth
    L2norm: True


DATALOADER:
    NUM_WORKERS: 7
    PIN_MEMORY: True


GRAPH_NET_PARAMS:
  node_agg_fn: 'sum'
  num_enc_steps: 4  # before 4 Number of message passing steps
  num_class_steps: 3  # before 3Number of message passing steps during feature vectors are classified (after Message Passing)
  reattach_initial_nodes: False  # elg. Original: False Determines whether initially encoded node feats are used during node updates
  reattach_initial_edges: False  #  elg. Original: TrueDetermines whether initially encoded edge feats are used during node updates

  encoder_feats_dict:
    edges:
      edge_in_dim: 4 # elg: 2 if only appearance
      edge_fc_dims: [ ] #elg before [6]
      edge_out_dim: 6 # elg: original = 16 ours 1 if not encoding

    nodes:
      resnet50:
        #NODE FEATURES ENCODER
        node_in_dim: 2048
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False

      bdnet_market:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      bdnet_cuhk:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [ 128 ]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      osnet_ms_c_d:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [128]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False #False
      osnet_market:

        #NODE FEATURES ENCODER
        node_in_dim: 512
        #node_fc_dims: [512, 128]
        node_fc_dims: [ 128 ]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False
      resnext101_cars:
        #NODE FEATURES ENCODER
        node_in_dim: 2048
        #node_fc_dims: [512, 128]
        node_fc_dims: [ 128 ]
        node_out_dim: 32
        dropout_p: 0
        use_batchnorm: False


  # MPN EDGE UPDATE
  edge_model_feats_dict:
    fc_dims: [6] #  before 66,6elg: orig [80,16]In size is 4 * encoded nodes + 2 * encoded edges
    dropout_p: 0
    use_batchnorm: False

 # MPN NODE UPDATE

  node_model_feats_dict:
    fc_dims: [32]  # elg: orig [56,32] In size is 2 * encoded nodes + 1 * encoded edges
    dropout_p: 0
    use_batchnorm: False

  classifier_feats_dict:
    edge_in_dim: 6 #orig 16
    edge_fc_dims: [4] # orig
    edge_out_dim: 1
    dropout_p: 0
    use_batchnorm: True


    # for geometrical association
NORM_TO_M: True
GEOM_TH:
  EPFL-Basketball: 250
  EPFL-Terrace: 80
  EPFL-Laboratory: 50


#FOR REID_th

MAX_DIST_L2:
  resnet50:
    EPFL-Basketball: 30.76
    EPFL-Terrace: 33.63
    EPFL-Laboratory: 33.79
  bdnet_market:
    EPFL-Basketball: 34.38
    EPFL-Terrace: 36.91
    EPFL-Laboratory: 39.68

OPT_TH:
  L2:
    resnet50:
      EPFL-Basketball: 0.63
      EPFL-Terrace: 0.59
      EPFL-Laboratory: 0.55
    bdnet_market:
      EPFL-Basketball: 0.62
      EPFL-Terrace: 0.55
      EPFL-Laboratory: 0.48
  COS:
    resnet50:
      EPFL-Basketball: 0.71
      EPFL-Terrace: 0.71
      EPFL-Laboratory: 0.75
    bdnet_market:
      EPFL-Basketball: 0.41
      EPFL-Terrace: 0.35
      EPFL-Laboratory: 0.42
